//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinWisper.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinWisper.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Add_Files {
            get {
                return ResourceManager.GetString("Add_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear filelist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Clear_Filelist {
            get {
                return ResourceManager.GetString("Clear_Filelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Complete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete selected items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete_Selected_Items {
            get {
                return ResourceManager.GetString("Delete_Selected_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MyWhisper に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FormTitle {
            get {
                return ResourceManager.GetString("FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file list is empty. Select the file you wish to transcribe from the menu. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_Empty_Filelist {
            get {
                return ResourceManager.GetString("Message_Empty_Filelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pro version is required to use the Large model. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_Need_Pro_Version {
            get {
                return ResourceManager.GetString("Message_Need_Pro_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Num Processes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Num_Processes {
            get {
                return ResourceManager.GetString("Num_Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Num Threads に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Num_Threads {
            get {
                return ResourceManager.GetString("Num_Threads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Output_Format {
            get {
                return ResourceManager.GetString("Output_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Transcribe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Start_Transcribe {
            get {
                return ResourceManager.GetString("Start_Transcribe", resourceCulture);
            }
        }
    }
}
